---
- name: Create SLATE directory
  file:
    dest: ~/.slate
    mode: 0700
    state: directory

- name: Create SLATE token
  copy:
    dest: ~/.slate/token
    mode: 0600
    content: "{{ slate_cli_token }}"

- name: Create SLATE endpoint
  copy:
    dest: ~/.slate/endpoint
    mode: 0600
    content: "{{ slate_cli_endpoint }}"

- name: Check if registered with SLATE
  shell: >-
    set -o pipefail;
    slate cluster list |
    awk 'BEGIN { found = 1 } NR>1 { if ($2 == "{{ slate_group_name }}") { if ($1 == "{{ slate_cluster_name }}") { found = 0; exit } } } END { print found }'
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
  args:
    executable: /bin/bash
  register: slate_registration_result
  changed_when: False

- name: Register cluster with SLATE
  shell: >-
    slate cluster create {{ slate_cluster_name }}
    --group '{{ slate_group_name }}'
    --org '{{ slate_org_name }}'
    -y
    {{ slate_enable_ingress | bool | ternary('', '--no-ingress') }}
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
  when: slate_registration_result.stdout != "0"
  # Timeout if it doesn't succeed in 3 minutes
  async: 180
  poll: 10
